version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - DockerLogin

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Authenticate with Docker
          command: |
            docker login --username ${DOCKER_USERNAME} -p "${DOCKER_PASSWORD}"
      - run:
          name: Build application Docker image
          command: |
            date +%Y%m%d_%H%M > /tmp/timestamp
            TS=`cat /tmp/timestamp`
            ##
            U="_"
            BRANCH="$CIRCLE_BRANCH$U$TS"
            ##
            echo $CIRCLE_BRANCH
            echo $BRANCH
            ##
            docker build -t ${IMAGE_REPO}/${IMAGE_NAME}:$CIRCLE_BRANCH -t ${IMAGE_REPO}/${IMAGE_NAME}:$BRANCH .
            ##
            docker push ${IMAGE_REPO}/${IMAGE_NAME}:$CIRCLE_BRANCH
            docker push ${IMAGE_REPO}/${IMAGE_NAME}:$BRANCH
